config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),
]

notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'
urlpatterns = [
    path('', views.index, name='home-page'),
    path('topics/', views.topics, name='topics'),
    path('entries/<int:topic_id>/', views.entries, name='entries'),
]

notes/models.py
from django.db import models


class Topic(models.Model):
    topic_theme = models.CharField(max_length=100)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.topic_theme


class Entry(models.Model):
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if len(self.text) < 50:
            return self.text
        else:
            return f"{self.text[:50]}..."

    class Meta:
        verbose_name_plural = 'entries'

notes/views.py
from django.shortcuts import render
from .models import Topic, Entry


def index(request):
    return render(request, 'notes/home_page.html')


def topics(request):
    topics = Topic.objects.all()
    context = {'topics': topics}
    return render(request, 'notes/topics.html', context=context)


def entries(request, topic_id):
    topic_entries = Topic.objects.get(id=topic_id).entry_set.order_by('-date_added')
    context = {'entries': topic_entries}
    return render(request, 'notes/entries.html', context=context)

notes/templates/notes/entries.html
{% extends 'base.html' %}

{% block notes %}
    <h1>Topic: {{ entries.topic }}</h1>
    <h1>Entries:</h1>
    <ul>
    {% for entry in entries %}
        <li>
            <p>{{ entry.date_added | date:'M d, Y H:i' }}</p>
            <p>{{ entry.text | linebreaks }}</p>
        </li>
    {% empty %}
        <li>There are no entries for the topic yet.</li>
    {% endfor %}
    </ul>


{% endblock notes %}

notes/templates/notes/home_page.html
{% extends 'base.html' %}

{% block notes %}
    <h1>Your Notes</h1>
    <p>You can keep your notes here.</p>
{% endblock notes %}

notes/templates/notes/topics.html
{% extends 'base.html' %}

{% block notes %}
<h1>Topics</h1>
  {% for topic in topics %}
    <li><a href="{% url 'notes:entries' topic.id %}">{{ topic.topic_theme }}</a></li>
  {% endfor %}
{% endblock notes %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Notes</title>
</head>
<body>
<p>
    <a href="{% url 'notes:home-page' %}">Notes</a>
    <a href="{% url 'notes:topics' %}">Topics</a>
</p>
    {% block notes %}
    {% endblock notes %}
</body>
</html>